builds:
  - main: cmd/dns-heaven/main.go
    binary: dns-heaven
    goos:
      - darwin
    goarch:
      - amd64
    ldflags: |-
      -X main.Version={{.Version}}

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
    - goos: windows
      format: zip
